### ISSUE TITLE
Integrate 'Schema.org Metatag' module?

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/metatag#27]
Drupal has a [Schema.org Metatag](https://www.drupal.org/project/schema_metatag) that extends Metatag with structured JSON LD data. Could/should we integrate that directly into Metatag?

**Comment by jenlampton** [comment]
I don't think so, I found the schema.org module mostly useless on my Drupal sites since it was intended to work with RDF (and didn't to a very good job at JSON-LD).  

For google rich text snippets I've been using the [Structured Data](https://github.com/backdrop-contrib/structured_data) module instead. And since JSON-LD in the header isn't really a metatag, I've found it sensible to manage it separately.
