### ISSUE TITLE
Warning: "Theme hook "metatag_http_equiv" not found."

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/metatag#30]
I keep seeing this warning in the site logs:

> Theme hook "metatag_http_equiv" not found.

Searching through the code shows a few calls to this, but no theme function for it...

**Comment by jenlampton** [comment]
There's no `theme_html_tag()` in Backdrop, so all these old theme functions need to be converted. 

Can you let me know what metatag submodules you are using? I'd like to play around with this, but my guess is that we'll need to do something like this PR.

**Comment by ghost** [comment]
@jenlampton The site where I'm seeing this only has the main Metatag module enabled, and the Metatag: OpenGraph sub-module.

**Comment by jenlampton** [comment]
Thanks, I'll start there :)

**Comment by alanmels** [comment]
Hitting the same issue with no additional modules enabled:
![Screen Shot 2021-12-01 at 1 38 11 PM](https://user-images.githubusercontent.com/56604405/144302094-90406066-81d5-47f1-a822-4e6ae883753b.png)

**Comment by alanmels** [comment]
This is the only development version module I use on a production Backdrop website, because of the reported issue. The PR takes care of the issue, however there were couple more occurrences of `metatag_http_equiv` theme hook calls, so it would be nice to also get rid of them before releasing another official version.
