### ISSUE TITLE
[node:field_image] as default even not in use

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/metatag#51]
The token [node:field_image] is being used in the opengraph submodule settings, even if that field is not being in use in the node. This causes the settings form to fail every time you update it, as reported originaly here: https://github.com/backdrop-contrib/metatag/issues/48

![image-field](https://user-images.githubusercontent.com/105581/87220921-49c6c580-c368-11ea-94a0-8dab1189401f.gif)

**Comment by jenlampton** [comment]
> I propose to not provide that default

Since this field is provided by default in core, I think this should be included by default in metatag also, it will save everyone the headache of trying to figure out how to get an image to appear when sharing to social media. A better approach would be to check if the field exists before setting the default, and if not, exclude it.

**Comment by robertgarrigos** [comment]
I close this.

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop-contrib/metatag/pull/100.
